Use CIS31014;

SELECT FIRST_NAME, LAST_NAME, CUST_ID, CREDIT_LIMIT

from CUSTOMER

WHERE CREDIT_LIMIT >=  1000;


SELECT FIRST_NAME, LAST_NAME, CUST_ID, REP_ID

From CUSTOMER

WHERE REP_ID IN ('10','15');

SELECT ITEM_ID, DESCRIPTION, CATEGORY

From ITEM

WHERE CATEGORY IN ('FSH','BRD');

SELECT CUST_ID, FIRST_NAME, LAST_NAME

From CUSTOMER

WHERE FIRST_NAME LIKE 'S%';